### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by reachyou91** [themains/pydomains#13]
I have a data frame consisting of URLs as below in column 'resolved_url'. The package works well overall (and successfully works when using DMOZ. However, I keep having **type error** when using PhishTank, Shalllist, Toulouse.

**Here are my URLs that I have 'resolved_url' column in my data frame.  This column does not have any NaN value.**
df['resolved_url']
Out[28]: 
0           http://giveaway.amazon.com\__CONNECTIONPOOL_ER...
1           https://twitter.com/tonythehuff/status/9271864...
2           http://giveaway.amazon.com\__CONNECTIONPOOL_ER...
3                 http://pcktpro.com\__CONNECTIONPOOL_ERROR__
Name: resolved_url, Length: 15486150, dtype: object

**Here are the error output below.**
`
df_toulouse = pred_toulouse(df, domain_names = 'resolved_domain')
Downloading Toulouse model data from the server (toulouse_cat_lstm_others_2017.h5)...
98%|█████████▊| 1600.0/1631.5 [00:00<00:00, 12499.23KB/s]
Downloading Toulouse vocab data from the server (toulouse_cat_vocab_others_2017.csv)...
96%|█████████▌| 64.0/66.625 [00:00<00:00, 8090.28KB/s]
Downloading Toulouse names data from the server (toulouse_cat_names_others_2017.csv)...
100%|█████████▉| 64.0/64.080078125 [00:00<?, ?KB/s]
Loading Toulouse model, vocab and names data file...
Traceback (most recent call last):

File "", line 1, in
df_toulouse = pred_toulouse(df, domain_names = 'resolved_domain')

File "C:\Users\Simon\anaconda3\lib\site-packages\pydomains\pred_toulouse.py", line 100, in pred_toulouse
df[col_domain] = df[domain_names].apply(lambda c: url2domain(c, exclude_subdomains=['www']))

File "C:\Users\Simon\anaconda3\lib\site-packages\pandas\core\series.py", line 4356, in apply
return SeriesApply(self, func, convert_dtype, args, kwargs).apply()

File "C:\Users\Simon\anaconda3\lib\site-packages\pandas\core\apply.py", line 1036, in apply
return self.apply_standard()

File "C:\Users\Simon\anaconda3\lib\site-packages\pandas\core\apply.py", line 1092, in apply_standard
mapped = lib.map_infer(

File "pandas_libs\lib.pyx", line 2859, in pandas._libs.lib.map_infer

File "C:\Users\Simon\anaconda3\lib\site-packages\pydomains\pred_toulouse.py", line 100, in
df[col_domain] = df[domain_names].apply(lambda c: url2domain(c, exclude_subdomains=['www']))

File "C:\Users\Simon\anaconda3\lib\site-packages\pydomains\utils.py", line 66, in url2domain
tld = tldextract.extract(url)

File "C:\Users\Simon\anaconda3\lib\site-packages\tldextract\tldextract.py", line 296, in extract
return TLD_EXTRACTOR(url, include_psl_private_domains=include_psl_private_domains)

File "C:\Users\Simon\anaconda3\lib\site-packages\tldextract\tldextract.py", line 216, in call
SCHEME_RE.sub("", url)

TypeError: expected string or bytes-like object
`

I suspect this issue occurs because some of processed URL after your algorithm with Toulouse is NaN, although I do not have any NaN value on original urls. I also look thorough the function between dmoz_cat and pred_toulouse and the code for dealing url strings seems similar so I don't know why this issue happens only for PhishTank, Shalllist, Toulouse, not Dmoz. 

This issue occurs when I use other PC installing the current version of your pydomains package.

**Comment by reachyou91** [comment]
I actually kinda resolve the problem by myself. As indicated in the error, your package works great if I change  "tldextract.py", line 216, 

SCHEME_RE.sub("", url) -> SCHEME_RE.sub("", **str**(url))

Other than that package works well! I really appreciate your work and will cite yours if I use this work on my research!

**Comment by soodoku** [comment]
super. we expect a string in that column so i won't do explicitly coerce to
string. glad that you have it working. we should have a better model for
pydomains soon.
