### ISSUE TITLE
Domain Analysis

### ISSUE THREAD

**Issue by Gautamshahi** [themains/pydomains#2]
Hello,

I have executed the code on the list of URL, but all the twitter related website are categorised as porn/adult category

example http://twitter.com/download/iphone or https://studio.twitter.com are porn category.

Any explanation?

**Comment by soodoku** [comment]
hey @Gautamshahi, 

the 'pred_' functions are based on systematic patterns in domain names only so it is bound to get a bunch wrong. 

I would recommend using other labeled data to get at the category of prominent domains and then to use pred for remaining. more here: http://www.gsood.com/research/papers/domain_knowledge.pdf

and for your use case, you may want to build an ML classifier that uses the content of the page to infer the category. for instance, the number of images over a certain size, text, etc.  see the last item of 'todo': 
https://github.com/themains/pydomains/blob/master/TODO

**Comment by Gautamshahi** [comment]
Hello, 

Thank you for the suggestion. I can work on it.

I think the pred function analyses the content and matches its similarity from the existing data(correct me if I am wrong), In any case, twitter.com is related to porn or adult website. 

Is it the fault of the model or the dataset?

Thank you for the paper, can you please share the citation of the paper(Domain Knowledge: Predicting the Kind of Content Hosted by a Domain)?

**Comment by soodoku** [comment]
Hey @Gautamshahi,

I am one of the co-authors of the package so I can say with confidence that the following is not true:
"I think the pred function analyses the content and matches its similarity from the existing data"

See paper for the underlying algorithm. 

Having said that, I would like to do something that uses content as I note in the to do but it needs time as it needs an entirely different pipeline. For instance, for each new prediction, there would be a live ping to the website that will download the data and then parse and then predict. All of it can be done but needs doing. If you are looking to work on anything or know someone who is, feel free to point them to me.

Cite for the paper:
```
@article{laohaprapanon2018domain,
  title={Domain Knowledge: Predicting the Kind of Content Hosted by a Domain},
  author={Laohaprapanon, Suriyan and Sood, Gaurav},
  year={2018}
}
```
